spring.application.name=workorder-scheduler-service
server.port=8081
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Production DB
# =========================

production.datasource.url=jdbc:mysql://localhost:3306/ProductionDB
production.datasource.username=root
production.datasource.password=Mysql123@
production.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# IDB
# =========================

idb.datasource.url=jdbc:mysql://localhost:3306/IDB
idb.datasource.username=root
idb.datasource.password=Mysql123@
idb.datasource.driver-class-name=com.mysql.cj.jdbc.Driver